export const COLORS = {
    BACKGROUND_ONE_COLOR: '#ccb578',
    BACKGROUND_TWO_COLOR: '#454236',
    BEZEL_ONE_BACKGROUND_COLOR: '#c5aa62',
    BEZEL_TWO_BACKGROUND_COLOR: '#ede3b3',
    DECORATION_BEZEL_ONE_COLOR: '#f3e7be',
    DECORATION_BEZEL_TWO_COLOR: '#553a1f',
    BLACK_COLOR: '#000000',
    WHITE_COLOR: '#ffffff',
    DIAL_DARK_COLOR: '#f3e7be',
    DIAL_LIGHT_COLOR: '#ead49e',
    HANDS_FIRST_COLOR: '#f1e4bc',
    HANDS_SECOND_COLOR: '#695d40',
    CASE_WATCH_COLOR: '#b7b9bc'
}