export const COLORS = {
    BACKGROUND_LIGHT_COLOR: '#fbe9b9',
    BACKGROUND_DARK_COLOR: '#49463a',
    BEZEL_LIGHT_BACKGROUND_COLOR: '#c5aa62',
    BEZEL_DARK_BACKGROUND_COLOR: '#ede3b3',
    DECORATION_BEZEL_LIGHT_COLOR: '#FFF0C1',
    DECORATION_BEZEL_DARK_COLOR: '#544415',
    BLACK_COLOR: '#000000',
    WHITE_COLOR: '#ffffff',
    DIAL_DARK_COLOR: '#919351',
    DIAL_LIGHT_COLOR: '#ffe8a9',
    HANDS_FIRST_COLOR: '#f1e4bc',
    HANDS_SECOND_COLOR: '#695d40',
    CASE_WATCH_COLOR: '#b7b9bc'
}